default: &default
  adapter: postgresql
  encoding: utf8
  port: 5432
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: backend_offer_review_development

test:
  <<: *default
  host: localhost
  database: backend_offer_review_test

production:
  <<: *default
  database: backend_offer_review_production
